# Fetching the node image on alpine
FROM node:18-alpine
# Setting the working directory
WORKDIR /react-app
# Installing the dependencies
COPY ./package.json /react-app
COPY ./package-lock.json /react-app

RUN npm install

# Copying the source code
COPY . /react-app

# Exposing the port
EXPOSE 3000

# Running the app
CMD ["npm", "start"]