apiVersion: apps/v1
kind: Deployment
metadata:
  name: display-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: display-service
  template:
    metadata:
      labels:
        app: display-service
    spec:
      containers:
        - name: display-service
          image: juliolt/display_service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: display-service
spec:
  type: NodePort
  selector:
    app: display-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      nodePort: 30080