apiVersion: apps/v1
kind: Deployment
metadata:
  name: operation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operation-service
  template:
    metadata:
      labels:
        app: operation-service
    spec:
      containers:
        - name: operation-service
          image: juliolt/operation_service:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: operation-service
spec:
  type: LoadBalancer
  selector:
    app: operation-service
  ports:
    - name: http
      protocol: TCP
      targetPort: 3000
      port: 8081
      nodePort: 30081